# Generated by Django 2.1.2 on 2019-06-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181115_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'núcleo'},
        ),
    ]
