# Generated by Django 2.1.2 on 2019-06-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='count',
            new_name='counter',
        ),
    ]
