# Generated by Django 2.1.15 on 2020-04-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190626_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Núcleos'},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
    ]
