# Generated by Django 2.1.2 on 2019-06-20 01:02

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_block',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do primeiro bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do texto 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do texto 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_block',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do primeiro bloco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_block_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do texto 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Titulo do texto 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 3'),
        ),
    ]
