# Generated by Django 2.1.2 on 2019-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_partnersgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersgalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nome do parceiro'),
        ),
    ]
