# Generated by Django 2.1.2 on 2019-06-23 23:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0007_auto_20190623_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoresPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_block', models.CharField(blank=True, max_length=255, verbose_name='Titulo inicial')),
                ('first_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto inicial')),
                ('second_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 1')),
                ('second_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('third_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 2')),
                ('third_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('fourth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 3')),
                ('fourth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('fifth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 4')),
                ('fifth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('sixth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 5')),
                ('sixth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('seventh_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 6')),
                ('seventh_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('eighth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 7')),
                ('eighth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('ninth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 8')),
                ('ninth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
                ('tenth_block', models.CharField(blank=True, max_length=255, verbose_name='Núcleo 9')),
                ('tenth_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do primeiro bloco'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do texto 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fourth_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do texto 4'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do segundo bloco'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do texto 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='third_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do texto 3'),
        ),
        migrations.AlterField(
            model_name='stdpage',
            name='first_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do primeiro bloco'),
        ),
        migrations.AlterField(
            model_name='stdpage',
            name='second_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do segundo bloco'),
        ),
        migrations.AlterField(
            model_name='stdpage',
            name='third_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titulo do terceiro bloco'),
        ),
    ]
