# Generated by Django 2.1.2 on 2019-06-24 00:30

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190623_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='corespage',
            name='eleventh_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='corespage',
            name='eleventh_block_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto 1'),
        ),
    ]
