# Generated by Django 2.1.2 on 2019-06-26 13:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190623_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('first_block', models.CharField(blank=True, max_length=255, verbose_name='Titulo inicial')),
                ('first_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto inicial')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores', to='home.CoresPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stdpage',
            name='first_block',
        ),
        migrations.RemoveField(
            model_name='stdpage',
            name='second_block',
        ),
        migrations.RemoveField(
            model_name='stdpage',
            name='second_block_text',
        ),
        migrations.RemoveField(
            model_name='stdpage',
            name='third_block',
        ),
        migrations.RemoveField(
            model_name='stdpage',
            name='third_block_text',
        ),
        migrations.AlterField(
            model_name='stdpage',
            name='first_block_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto'),
        ),
    ]
