# Generated by Django 2.1.2 on 2019-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190626_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corespage',
            name='eighth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='eighth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='eleventh_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='eleventh_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='fifth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='fifth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='fourth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='fourth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='ninth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='ninth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='seventh_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='seventh_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='sixth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='sixth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='tenth_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='tenth_block_text',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='third_block',
        ),
        migrations.RemoveField(
            model_name='corespage',
            name='third_block_text',
        ),
        migrations.AlterField(
            model_name='corespage',
            name='second_block',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
