# Generated by Django 2.1.2 on 2019-06-26 14:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190626_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('first_block', models.CharField(blank=True, max_length=255, verbose_name='Titulo inicial')),
                ('first_block_text', wagtail.core.fields.RichTextField(blank=True, verbose_name='Texto inicial')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='home.CoresPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='core',
            name='page',
        ),
        migrations.DeleteModel(
            name='Core',
        ),
    ]
